export const dataExportSections = [
  "profile",
  "clients",
  "leads",
  "followUps",
  "services",
  "bookings",
  "jobs",
  "staff",
  "quotes",
  "estimates",
  "invoices",
  "payments",
  "expenses",
  "websiteSubmissions",
] as const;

export type DataExportSection = (typeof dataExportSections)[number];

export const profileExportSelect = {
  id: true,
  businessName: true,
  businessLogo: true,
  brandColor: true,
  businessEmail: true,
  mobileNumber: true,
  address: true,
  city: true,
  zipcode: true,
  country: true,
  currency: true,
  businessType: true,
  licenseNumber: true,
  businessDescription: true,
  website: true,
  businessHours: true,
  onboardingCompletedSteps: true,
  onboardingCompletedAt: true,
  skippedSteps: true,
  createdAt: true,
  updatedAt: true,
  user: {
    select: {
      id: true,
      name: true,
      email: true,
      role: true,
      status: true,
      createdAt: true,
      updatedAt: true,
    },
  },
} as const;

export const clientExportSelect = {
  id: true,
  name: true,
  email: true,
  phone: true,
  status: true,
  servicePreference: true,
  addressLine1: true,
  addressLine2: true,
  city: true,
  zipcode: true,
  country: true,
  totalSpend: true,
  totalBookings: true,
  lastBookingDate: true,
  latitude: true,
  longitude: true,
  geocodedAt: true,
  createdAt: true,
  updatedAt: true,
} as const;

export const leadExportSelect = {
  id: true,
  leadRef: true,
  name: true,
  email: true,
  phone: true,
  serviceInterest: true,
  serviceCatalogId: true,
  estimatedMin: true,
  estimatedMax: true,
  stage: true,
  notes: true,
  sourceRef: true,
  sourceWebsiteId: true,
  convertedClientId: true,
  convertedAt: true,
  lastContactedAt: true,
  createdAt: true,
  updatedAt: true,
} as const;

export const followUpExportSelect = {
  id: true,
  leadId: true,
  type: true,
  status: true,
  scheduledAt: true,
  completedAt: true,
  assignedToUserId: true,
  note: true,
  outcome: true,
  createdBy: true,
  createdAt: true,
  updatedAt: true,
  lead: { select: { leadRef: true, name: true, email: true } },
  assignedTo: { select: { name: true, email: true } },
} as const;

export const serviceExportSelect = {
  id: true,
  serviceName: true,
  description: true,
  basePrice: true,
  duration: true,
  category: true,
  status: true,
  onlineBookingEnabled: true,
  legacyServiceType: true,
  addOns: true,
  createdAt: true,
  updatedAt: true,
} as const;

export const bookingExportSelect = {
  id: true,
  bookingRef: true,
  status: true,
  serviceType: true,
  serviceCatalogId: true,
  serviceNameSnapshot: true,
  priceSnapshot: true,
  durationSnapshot: true,
  addOnSnapshot: true,
  address: true,
  scheduledDate: true,
  durationMins: true,
  total: true,
  notes: true,
  clientId: true,
  quoteId: true,
  recurringScheduleId: true,
  createdAt: true,
  updatedAt: true,
  client: { select: { name: true, email: true } },
  staffAssignments: {
    select: {
      staffId: true,
      staff: { select: { user: { select: { name: true, email: true } } } },
    },
  },
} as const;

export const jobExportSelect = {
  id: true,
  jobRef: true,
  status: true,
  serviceType: true,
  serviceCatalogId: true,
  serviceNameSnapshot: true,
  priceSnapshot: true,
  durationSnapshot: true,
  address: true,
  latitude: true,
  longitude: true,
  geocodedAt: true,
  scheduledDate: true,
  durationMins: true,
  notes: true,
  quoteId: true,
  estimateId: true,
  bookingId: true,
  clientId: true,
  createdAt: true,
  updatedAt: true,
  client: { select: { name: true, email: true } },
  staffAssignments: {
    select: {
      staffId: true,
      checkInAt: true,
      checkOutAt: true,
      hoursWorked: true,
      staff: { select: { user: { select: { name: true, email: true } } } },
    },
  },
} as const;

export const staffExportSelect = {
  id: true,
  userId: true,
  staffRole: true,
  mobileNumber: true,
  address: true,
  latitude: true,
  longitude: true,
  geocodedAt: true,
  hourlyRate: true,
  startDate: true,
  specialty: true,
  status: true,
  manuallyInactive: true,
  emergencyName: true,
  emergencyMobileNumber: true,
  adminNote: true,
  createdAt: true,
  updatedAt: true,
  user: { select: { name: true, email: true, status: true } },
} as const;

export const quoteExportSelect = {
  id: true,
  quoteRef: true,
  status: true,
  serviceType: true,
  serviceCatalogId: true,
  serviceNameSnapshot: true,
  address: true,
  subtotal: true,
  taxRate: true,
  tax: true,
  total: true,
  validUntil: true,
  notes: true,
  internalNotes: true,
  sentAt: true,
  respondedAt: true,
  responseNote: true,
  clientId: true,
  createdAt: true,
  updatedAt: true,
  client: { select: { name: true, email: true } },
  lineItems: { select: { description: true, quantity: true, unitPrice: true, total: true } },
} as const;

export const estimateExportSelect = {
  id: true,
  estimateRef: true,
  status: true,
  serviceType: true,
  serviceCatalogId: true,
  serviceNameSnapshot: true,
  address: true,
  labourCost: true,
  materialCost: true,
  overheadCost: true,
  marginPercent: true,
  subtotal: true,
  taxRate: true,
  tax: true,
  total: true,
  validUntil: true,
  notes: true,
  internalNotes: true,
  sentAt: true,
  respondedAt: true,
  responseNote: true,
  convertedToBookingRef: true,
  convertedToQuoteRef: true,
  clientId: true,
  createdAt: true,
  updatedAt: true,
  client: { select: { name: true, email: true } },
  lineItems: { select: { description: true, quantity: true, unitPrice: true, total: true } },
} as const;

export const invoiceExportSelect = {
  id: true,
  invoiceRef: true,
  status: true,
  clientName: true,
  clientEmail: true,
  serviceAddress: true,
  linkedBookingRef: true,
  serviceCatalogId: true,
  serviceNameSnapshot: true,
  lineItems: true,
  notes: true,
  issuedDate: true,
  dueDate: true,
  paidDate: true,
  sentAt: true,
  subtotal: true,
  taxRate: true,
  taxAmount: true,
  total: true,
  bookingId: true,
  createdAt: true,
  updatedAt: true,
} as const;

export const paymentExportSelect = {
  id: true,
  paymentRef: true,
  amount: true,
  currency: true,
  method: true,
  status: true,
  note: true,
  transactionId: true,
  refundAmount: true,
  invoiceId: true,
  paidAt: true,
  approvedAt: true,
  approvedByUserId: true,
  rejectionReason: true,
  createdAt: true,
  updatedAt: true,
  invoice: { select: { invoiceRef: true, clientName: true, clientEmail: true } },
} as const;

export const expenseExportSelect = {
  id: true,
  expenseRef: true,
  description: true,
  category: true,
  amount: true,
  date: true,
  paidBy: true,
  isRecurring: true,
  notes: true,
  createdAt: true,
  updatedAt: true,
} as const;

export const bookingSubmissionExportSelect = {
  id: true,
  ref: true,
  status: true,
  serviceType: true,
  serviceCatalogId: true,
  serviceNameSnapshot: true,
  priceSnapshot: true,
  durationSnapshot: true,
  addOnIds: true,
  addOnSnapshot: true,
  totalSnapshot: true,
  sourceWebsiteId: true,
  source: true,
  sourcePage: true,
  utmSource: true,
  utmCampaign: true,
  propertyType: true,
  bedrooms: true,
  bathrooms: true,
  date: true,
  timeSlot: true,
  name: true,
  email: true,
  phone: true,
  address: true,
  notes: true,
  answers: true,
  formId: true,
  convertedBookingId: true,
  convertedAt: true,
  createdAt: true,
} as const;

export const estimateSubmissionExportSelect = {
  id: true,
  ref: true,
  status: true,
  serviceType: true,
  serviceCatalogId: true,
  serviceNameSnapshot: true,
  priceSnapshot: true,
  durationSnapshot: true,
  addOnIds: true,
  pricingSnapshot: true,
  sourceWebsiteId: true,
  bedrooms: true,
  bathrooms: true,
  postcode: true,
  city: true,
  name: true,
  email: true,
  phone: true,
  notes: true,
  answers: true,
  estimatedMin: true,
  estimatedMax: true,
  formId: true,
  createdAt: true,
} as const;
