export const DEFAULT_WEBSITE_SETTINGS = Object.freeze({
  templateId: "clean-modern",
  primaryColor: "#0F766E",
  secondaryColor: "#0F172A",
  accentColor: "#14B8A6",
  font: null as string | null,
  logo: null as string | null,
  favicon: null as string | null,
  bookingEnabled: false,
  bookingShowHeaderCta: true,
  bookingShowServiceCtas: true,
  bookingShowHomeCta: true,
  bookingShowAvailableSlots: true,
  bookingShowPrices: true,
  estimateEnabled: false,
  metaTitle: null as string | null,
  metaDescription: null as string | null,
  socialImageUrl: null as string | null,
  indexSite: true,
});

export const RESERVED_WEBSITE_SUBDOMAINS = new Set([
  "www", "admin", "api", "app", "dashboard", "support", "billing",
  "login", "register", "mail", "static", "assets", "cdn", "status",
  "help", "docs", "blog", "portal", "site", "sites", "auth",
]);

/**
 * Default content is intentionally generic and contains no tenant data.
 * The public runtime overlays dynamic CRM data (business profile, services,
 * reviews and service areas) so a newly provisioned website is useful without
 * duplicating those records into website JSON.
 */
export const DEFAULT_WEBSITE_PAGES = [
  {
    kind: "HOME",
    slug: "/",
    title: "Home",
    showInNavigation: true,
    sortOrder: 0,
    content: {
      eyebrow: "Professional cleaning services",
      heroTitle: "A cleaner space, without the stress.",
      heroSubtitle: "Reliable local cleaning with simple online booking and friendly support.",
      primaryCtaLabel: "Book a clean",
      secondaryCtaLabel: "Get free estimate",
      servicesHeading: "Cleaning services built around your space",
      servicesIntro: "Choose from services maintained in our live cleaning catalog.",
      aboutHeading: "Professional, dependable and easy to book",
      aboutBody: "We focus on clear communication, dependable service and a consistently high standard of cleaning.",
      whyHeading: "Why customers choose us",
      whyIntro: "A straightforward cleaning experience from first enquiry to finished job.",
      whyItems: [
        { title: "Reliable service", description: "Clear communication and dependable scheduling from a professional cleaning team." },
        { title: "Live service information", description: "Services and pricing stay connected to the same CRM catalog used by the business." },
        { title: "Customer feedback", description: "Published testimonials come from moderated CRM reviews rather than copied website content." },
        { title: "Easy online access", description: "Eligible services can flow directly into the business online booking experience." },
      ],
      reviewsHeading: "What customers say",
      reviewsIntro: "Recent published customer feedback from our cleaning CRM.",
      areasHeading: "Areas we cover",
      contactHeading: "Questions before you book?",
      contactBody: "Contact our team and we will help you choose the right cleaning service.",
      finalCtaHeading: "A cleaner space is a few clicks away.",
      footerDescription: "Professional cleaning services with clear communication, current service information and simple online access.",
      footerTrustText: "Service information is maintained directly by the cleaning business.",
      socialLinks: {},
    },
  },
  {
    kind: "SERVICES",
    slug: "/services",
    title: "Services",
    showInNavigation: true,
    sortOrder: 10,
    content: {
      eyebrow: "Our services",
      heading: "Cleaning services for homes and businesses",
      intro: "Choose the service that fits your space. Pricing and availability come directly from our live service catalog.",
    },
  },
  {
    kind: "ABOUT",
    slug: "/about",
    title: "About",
    showInNavigation: true,
    sortOrder: 20,
    content: {
      eyebrow: "About us",
      heading: "Cleaning you can feel confident booking",
      body: "We make professional cleaning straightforward: clear services, reliable scheduling and a team focused on doing the job properly.",
      values: ["Reliable service", "Clear communication", "Attention to detail"],
      imageUrl: null,
      imageAlt: "Professional cleaning team",
      yearsExperience: null,
    },
  },
  {
    kind: "REVIEWS",
    slug: "/reviews",
    title: "Reviews",
    showInNavigation: true,
    sortOrder: 30,
    content: {
      eyebrow: "Customer reviews",
      heading: "Trusted by the people we clean for",
      intro: "Published reviews shown here come directly from our customer feedback in the CRM.",
    },
  },
  {
    kind: "CONTACT",
    slug: "/contact",
    title: "Contact",
    showInNavigation: true,
    sortOrder: 40,
    content: {
      eyebrow: "Contact",
      heading: "How can we help?",
      intro: "Call or email us with a question, or use online booking when you are ready to arrange a clean.",
    },
  },
  {
    kind: "BOOK",
    slug: "/book",
    title: "Book",
    showInNavigation: false,
    isEnabled: false,
    sortOrder: 50,
    content: {},
  },
  {
    kind: "ESTIMATE",
    slug: "/estimate",
    title: "Estimate",
    showInNavigation: false,
    isEnabled: false,
    sortOrder: 60,
    content: {},
  },
] as const;
