export const DEFAULT_WEBSITE_SETTINGS = Object.freeze({
  templateId: "clean-modern",
  primaryColor: "#0F766E",
  secondaryColor: "#0F172A",
  accentColor: "#14B8A6",
  font: null as string | null,
  logo: null as string | null,
  favicon: null as string | null,
  bookingEnabled: false,
  bookingShowNavigation: true,
  bookingShowHeaderCta: true,
  bookingShowServiceCtas: true,
  bookingShowHomeCta: true,
  bookingShowAvailableSlots: true,
  bookingShowPrices: true,
  bookingShowStartingPrices: true,
  bookingShowServiceDuration: true,
  bookingCtaLabel: "Book Now",
  estimateEnabled: false,
  metaTitle: null as string | null,
  metaDescription: null as string | null,
  metaKeywords: [] as string[],
  socialImageUrl: null as string | null,
  indexSite: true,
  googleAnalyticsEnabled: false,
  googleAnalyticsMeasurementId: null as string | null,
});

export const RESERVED_WEBSITE_SUBDOMAINS = new Set([
  "www", "admin", "api", "app", "dashboard", "support", "billing",
  "login", "register", "mail", "static", "assets", "cdn", "status",
  "help", "docs", "blog", "portal", "site", "sites", "auth",
]);

/**
 * Default page copy is deliberately factual and claim-free. New websites must
 * not imply experience, reliability, certifications, insurance, ratings or
 * pricing that the tenant has not supplied. Public renderers overlay live CRM
 * services, prices, reviews, service areas and business details.
 */
export const DEFAULT_WEBSITE_PAGES = [
  {
    kind: "HOME",
    slug: "/",
    title: "Home",
    showInNavigation: true,
    sortOrder: 0,
    content: {
      eyebrow: "Cleaning services",
      heroTitle: "Cleaning services for your space.",
      heroSubtitle: "Browse the current service catalog and service areas, or contact the business with a question.",
      primaryCtaLabel: "Book online",
      secondaryCtaLabel: "Request an estimate",
      servicesHeading: "Current cleaning services",
      servicesIntro: "Service details shown on the website come from the business service catalog.",
      aboutHeading: "About the business",
      aboutBody: "",
      whyHeading: "Business information",
      whyIntro: "",
      whyItems: [],
      reviewsHeading: "Customer reviews",
      reviewsIntro: "Published customer feedback from this business.",
      areasHeading: "Service areas",
      contactHeading: "Contact the business",
      contactBody: "Ask about services, availability or whether an address is covered.",
      finalCtaHeading: "Ready to get in touch?",
      footerDescription: "",
      footerTrustText: "",
      socialLinks: {},
    },
  },
  {
    kind: "SERVICES",
    slug: "/services",
    title: "Services",
    showInNavigation: true,
    sortOrder: 10,
    content: {
      eyebrow: "Services",
      heading: "Current cleaning services",
      intro: "Service details are shown from the business service catalog; pricing and duration appear only when published.",
    },
  },
  {
    kind: "ABOUT",
    slug: "/about",
    title: "About",
    showInNavigation: true,
    sortOrder: 20,
    content: {
      eyebrow: "About",
      heading: "About the business",
      body: "",
      values: [],
      imageUrl: null,
      imageAlt: "",
      yearsExperience: null,
    },
  },
  {
    kind: "REVIEWS",
    slug: "/reviews",
    title: "Reviews",
    showInNavigation: true,
    sortOrder: 30,
    content: {
      eyebrow: "Customer reviews",
      heading: "Published customer reviews",
      intro: "Reviews appear here only after they have been published by the business.",
    },
  },
  {
    kind: "CONTACT",
    slug: "/contact",
    title: "Contact",
    showInNavigation: true,
    sortOrder: 40,
    content: {
      eyebrow: "Contact",
      heading: "Contact the business",
      intro: "Use the published contact details or enquiry form to ask about services and availability.",
    },
  },
  {
    kind: "BOOK",
    slug: "/book",
    title: "Book Online",
    showInNavigation: false,
    isEnabled: false,
    sortOrder: 50,
    content: {},
  },
  {
    kind: "ESTIMATE",
    slug: "/estimate",
    title: "Estimate",
    showInNavigation: false,
    isEnabled: false,
    sortOrder: 60,
    content: {},
  },
] as const;
