import { EventEmitter } from "node:events";
import { beforeEach, describe, expect, it, vi } from "vitest";
import type { Request, Response } from "express";
const mocks=vi.hoisted(()=>({log:vi.fn(),metric:vi.fn(),trace:{requestId:"req-phase3-123",traceId:"0123456789abcdef0123456789abcdef",authDurationMs:4,dbDurationMs:7,dbQueryCount:2,redisDurationMs:0,redisCommandCount:0,redisHits:0,redisMisses:0,redisErrors:0,responseCacheHits:0,responseCacheMisses:0,queueDurationMs:0,externalDurationMs:0}}));
vi.mock("../lib/logger",()=>({default:{log:mocks.log,warn:vi.fn()}}));
vi.mock("../lib/monitoring/performanceMetrics",()=>({recordRequestMetric:mocks.metric}));
vi.mock("../lib/monitoring/requestTrace",()=>({getRequestTrace:()=>mocks.trace,recordTraceRequestPhases:vi.fn()}));
vi.mock("../config/ENV",()=>({DEPLOYMENT_PROFILE:"primary-region",NODE_ENV:"production",RELEASE_VERSION:"release-phase3-test",SLOW_REQUEST_THRESHOLD_MS:1000}));
import logRequestResponse from "./logger.middleware";
class FakeResponse extends EventEmitter { statusCode=401; locals:Record<string,unknown>={requestId:"req-phase3-123",traceId:"0123456789abcdef0123456789abcdef",authErrorCode:"INVALID_CREDENTIALS"}; headersSent=false; headers=new Map<string,unknown>(); send=vi.fn((b:unknown)=>b); setHeader(n:string,v:unknown){this.headers.set(n.toLowerCase(),v);return this;} getHeader(n:string){return this.headers.get(n.toLowerCase());}}
beforeEach(()=>vi.clearAllMocks());
describe("auth observability privacy contract",()=>{it("logs correlation/code/release without credentials, OTP or email",()=>{const req={method:"POST",originalUrl:"/api/v1/auth/login",path:"/api/v1/auth/login",baseUrl:"",route:undefined,get:(name:string)=>name.toLowerCase()==="x-vercel-ip-country"?"US":undefined,body:{email:"jamie@example.com",password:"NeverLogPassword",otp:"987654",accessToken:"NeverLogAccess",refreshToken:"NeverLogRefresh",sessionToken:"NeverLogSession"}} as unknown as Request; const res=new FakeResponse() as unknown as Response; const next=vi.fn(); logRequestResponse(req,res,next); (res.send as unknown as (b:unknown)=>unknown)({success:false,code:"INVALID_CREDENTIALS"}); (res as unknown as EventEmitter).emit("finish"); expect(next).toHaveBeenCalledOnce(); expect(mocks.log).toHaveBeenCalledWith("info","http_request",expect.objectContaining({route:"/api/v1/auth/login",method:"POST",statusCode:401,requestId:"req-phase3-123",traceId:"0123456789abcdef0123456789abcdef",authErrorCode:"INVALID_CREDENTIALS",releaseSha:"release-phase3-test",deploymentProfile:"primary-region",market:"USA",countryCode:"US"})); const out=JSON.stringify(mocks.log.mock.calls); for(const secret of ["jamie@example.com","NeverLogPassword","987654","NeverLogAccess","NeverLogRefresh","NeverLogSession"]) expect(out).not.toContain(secret);});});
