import { rateLimit } from "express-rate-limit";
import type { NextFunction, Request, Response } from "express";
import { RedisRateLimitStore } from "../lib/rateLimit/redisRateLimitStore";

const WINDOW_MS = 15 * 60 * 1000;

const jsonMessage = (message: string) => ({
    success: false,
    message,
    error: { code: "PUBLIC_RATE_LIMITED", retryable: true },
});

const base = {
    windowMs: WINDOW_MS,
    standardHeaders: "draft-8" as const,
    legacyHeaders: false,
};

const store = (prefix: string) => new RedisRateLimitStore({
    prefix,
    windowMs: WINDOW_MS,
});

/** Per-IP distributed protection for unauthenticated reads. */
export const publicReadRateLimit = rateLimit({
    ...base,
    limit: 180,
    store: store("public-read"),
    message: jsonMessage("Too many requests. Please try again shortly."),
});

/** Per-IP distributed protection for unauthenticated writes/calculations. */
export const publicMutationRateLimit = rateLimit({
    ...base,
    limit: 30,
    store: store("public-write"),
    message: jsonMessage("Too many submissions. Please wait and try again."),
});

/**
 * A second limiter protects each public resource/tenant even when abusive
 * traffic is distributed across many IPs. Route params are opaque public
 * identifiers; no tenant database lookup is required in middleware.
 */
export const publicResourceMutationRateLimit = rateLimit({
    ...base,
    limit: 240,
    store: store("public-resource-write"),
    keyGenerator: (req: Request) => {
        const key = req.params.identifier ?? req.params.slug ?? req.params.token ?? "public";
        return `public-resource:${String(key).toLowerCase().slice(0, 160)}`;
    },
    message: jsonMessage("This public form is receiving too many requests. Please try again shortly."),
});

/**
 * Host-resolution traffic is generated by the frontend edge/proxy, so a
 * traditional per-IP limit can incorrectly group many visitors behind one
 * platform egress address. Limit by requested host/label instead.
 */
export const publicHostResolveRateLimit = rateLimit({
    ...base,
    limit: 1200,
    store: store("public-host-resolve"),
    keyGenerator: (req: Request) => {
        const key = req.params.host ?? req.params.subdomain ?? "host";
        return `public-host:${String(key).toLowerCase().slice(0, 253)}`;
    },
    message: jsonMessage("Too many website routing requests. Please try again shortly."),
});

/** High-volume but bounded telemetry per visitor/IP. */
export const publicTelemetryRateLimit = rateLimit({
    ...base,
    limit: 180,
    store: store("public-telemetry"),
    message: jsonMessage("Too many telemetry requests. Please try again shortly."),
});

/**
 * Stops distributed telemetry/error-report floods from targeting one tenant
 * while preserving enough headroom for normal page-view analytics.
 */
export const publicResourceTelemetryRateLimit = rateLimit({
    ...base,
    limit: 2_000,
    store: store("public-resource-telemetry"),
    keyGenerator: (req: Request) => {
        const key = req.params.identifier ?? "public";
        return `public-telemetry-resource:${String(key).toLowerCase().slice(0, 160)}`;
    },
    message: jsonMessage("This website is receiving too many telemetry requests. Please try again shortly."),
});

/**
 * Public token responses (quotes/reviews) may contain customer-specific data.
 * Prevent browsers, CDNs and intermediary proxies from storing those payloads.
 */
export const publicSensitiveNoStore = (_req: Request, res: Response, next: NextFunction) => {
    res.setHeader("Cache-Control", "no-store, max-age=0");
    res.setHeader("Pragma", "no-cache");
    res.setHeader("X-Content-Type-Options", "nosniff");
    next();
};
