import { Router, type NextFunction, type Request, type Response } from "express";
import status from "http-status";
import { prisma } from "../../lib/prisma/prisma";

/**
 * Minimal staging-only browser-test hooks.
 *
 * These routes deliberately do not provision services, onboarding state,
 * subscriptions, websites, forms, or other business data. The Playwright smoke
 * suite must exercise the production UI/API paths for those behaviours.
 *
 * Production safety is enforced twice: this router is mounted only outside
 * production and the middleware below independently fails closed with 404.
 */
const router = Router();
const token = process.env.E2E_TEST_TOKEN?.trim() || "";
const domain = (process.env.E2E_TEST_EMAIL_DOMAIN || "e2e.invalid")
  .trim()
  .toLowerCase();

const assertSyntheticEmail = (email: unknown): string => {
  const normalized = String(email || "").trim().toLowerCase();
  if (!normalized.endsWith(`@${domain}`)) {
    throw Object.assign(new Error("Synthetic E2E email required"), {
      statusCode: status.BAD_REQUEST,
    });
  }
  return normalized;
};

router.use((req: Request, res: Response, next: NextFunction) => {
  if (
    process.env.NODE_ENV === "production" ||
    process.env.E2E_TEST_HOOKS_ENABLED !== "true"
  ) {
    return res.status(status.NOT_FOUND).end();
  }

  if (token.length < 32 || req.get("x-e2e-token") !== token) {
    return res.status(status.NOT_FOUND).end();
  }

  next();
});

/** Retrieve only the OTP generated by the real registration/reset flow. */
router.get("/verification-code", async (req, res, next) => {
  try {
    const email = assertSyntheticEmail(req.query.email);
    const rows = await prisma.verification.findMany({
      where: { expiresAt: { gt: new Date() } },
      orderBy: { createdAt: "desc" },
      take: 100,
    });
    const row = rows.find((candidate) =>
      candidate.identifier.toLowerCase().includes(email),
    );

    if (!row || !/^\d{6}$/.test(row.value)) {
      return res.status(status.CONFLICT).json({
        success: false,
        message: "OTP not available yet",
      });
    }

    return res.json({ success: true, data: { otp: row.value } });
  } catch (error) {
    next(error);
  }
});

/** Delete the synthetic user created by a smoke journey after the test ends. */
router.post("/cleanup", async (req, res, next) => {
  try {
    const email = assertSyntheticEmail(req.body.email);
    await prisma.user.deleteMany({ where: { email } });
    return res.json({ success: true });
  } catch (error) {
    next(error);
  }
});

export const e2eTestRoutes = router;
